name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master', whatever you're using

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build your site
        run: |
          echo "Add your build commands here"
          # Example: npm install && npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist  # or wherever your built files go

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
